DROP TABLE rentals PURGE;
DROP TABLE appearances PURGE;
DROP TABLE actors PURGE;
DROP TABLE items PURGE;
DROP TABLE customers PURGE;
DROP TABLE movies PURGE;

DROP SEQUENCE itm_seq;
DROP SEQUENCE atr_seq;
DROP SEQUENCE ctr_seq;
DROP SEQUENCE mve_seq;
